language: elixir
elixir:
  - 1.10
  - 1.9
otp_release:
  - 22.2
  - 21.3
sudo: false
env:
  - CI=true
before_script:
  - epmd -daemon
  - mix deps.get
script:
  - mix compile --warnings-as-errors
  - mix credo --strict
  - mix format --check-formatted
  - MIX_ENV=test mix coveralls.travis
  - mix dialyzer --plt
  - mix dialyzer --halt-exit-status
after_script:
  - MIX_ENV=docs mix inch.report
