language: elixir
elixir:
  - 1.4.5
  - 1.3.4
otp_release:
  - 20.0
  - 19.3
  - 18.3
sudo: false
env:
  - MIX_ENV=test
matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
