language: elixir
elixir:
  - 1.4.4
  - 1.3.4
otp_release:
  - 19.3
  - 18.3
sudo: false
env:
  - MIX_ENV=test
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
